### ISSUE TITLE
MdCharm - Copy Issue

### ISSUE THREAD

**Issue by montypelerin** [zhangshine/MdCharm#1]
Very much like the software but have two issues:
1. Unable to copy anything from outside MdCharm into it. I suspect this is a problem at my end because I have the same issue with MarkdownPad2 (but not with Notepad**). Any idea what is causing it and how to fix it?
2. How do I register my copy and what does it cost to do so?

Thanks, for any help you can provide.

Monty

**Comment by zhangshine** [comment]
1. Sorry, I have no idea about it.
2. Download a new one from https://github.com/zhangshine/MdCharm/releases

**Comment by montypelerin** [comment]
Thanks for your response. Unfortunately it made no difference.

Still appreciate your work on the software. Just makes for non-existent cut
and pasting.

On Mon, May 26, 2014 at 9:09 PM, zhangshine notifications@github.comwrote:

> 1. Sorry, I have no idea about it.
> 2. Download a new one from
>    https://github.com/zhangshine/MdCharm/releases
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zhangshine/MdCharm/issues/1#issuecomment-44227136
> .

## 

“In the long run we are all dead. But unfortunately nearly all of us
outlive the short run. We are destined to spend decades paying for the easy
money orgy of a few years.”
by Ludwig von Mises
