### ISSUE TITLE
Hide extentions in project view

### ISSUE THREAD

**Issue by Doctor-Andonuts** [zhangshine/MdCharm#13]
Would it be possible to add an option to hide extensions in the project view?

**Comment by zhangshine** [comment]
Markdown file extensions only ?

**Comment by Doctor-Andonuts** [comment]
Using this mostly in windows, it would be neat to follow the windows setting "Hide extensions for known file types" if they have it set.  Though I realize that doesn't really work for Linux and may be awkward or confusing for other users.

Hiding just markdown extensions would make me happy =).  The icon makes it clear to me what the file type is.

Thanks for your work on MdCharm, BTW.  Best Markdown viewer/editor I have used yet.
