### ISSUE TITLE
Can't delete a project

### ISSUE THREAD

**Issue by ColinChrist** [zhangshine/MdCharm#34]
There is no obvius way to delete a project

**Comment by jmalarcon** [comment]
Hi:

Yes, this a bummer. 

However I've found a way to fix it. You can delete it this way:
1. Go to `C:\Users\[yourusername]\Roaming\MdCharm`
2. Open `session.xml`
3. Delete the contents of the `dirpath` attribute in the `Project`node of this XML file.

You're done.

If you want to delete all trace of the folder, do this:
1. Again, go to `C:\Users\[yourusername]\Roaming\MdCharm`
2. Open `MdCharm.ini`
3. Locate the section `[MdCharmState]`
4. Delete the contents of the key `LastOpenDir`
5. Locate the section `[LastState]`
6. Delete the contents of the key `MdCharmForm_OpenDirectory`

You're done!

HTH

**Comment by ColinChrist** [comment]
Thanx for that advice!!! :-)
