### ISSUE TITLE
预览时的宽度

### ISSUE THREAD

**Issue by ylme** [zhangshine/MdCharm#35]
预览时的宽度好像只能显示38个汉字就会被自动换行了。这个可以调吗？

**Comment by walkonroad** [comment]
#### 这个在Settings->preference->Styles里面修改CSS样式就行，全删了留这个，这是最霸道的方式，其他方式你可以再研究

body {
    margin: 0 auto;
    font-family: GB2312;
    color: #444444;
    line-height: 1.6;
    max-width: 100%;
    padding-left: 20%;
    padding-right: 20%;
}
![image](https://cloud.githubusercontent.com/assets/18378551/16571530/b0cc992e-4290-11e6-87d1-55a60029657e.png)
