### ISSUE TITLE
mdcharm deb安装好后,启动不了

### ISSUE THREAD

**Issue by hanalice** [zhangshine/MdCharm#36]
mdcharm deb安装好后,启动不了,系统为ubuntu 14.04

**Comment by qianlnk** [comment]
it can't run at ubuntu16.04. also.

**Comment by hanalice** [comment]
hello zhangshine,

我的是ubuntu14.04系统, 也不能使用.

At 2016-09-23 13:44:37, "qianlnk" notifications@github.com wrote:

it can't run at ubuntu16.04. also.

**Comment by zhangshine** [comment]
@hanalice @qianlnk 抱歉啊，这个项目已经废弃了。现在其他的markdown编辑器挺多的，参考一下这个吧 https://www.v2ex.com/t/293827

**Comment by Mapaler** [comment]
我下了老多，觉得是最好用的一个，居然废弃了

**Comment by scott-he** [comment]
@Mapaler  有同感，我也觉得这个最好用，但是居然停止更新了。

**Comment by Mapaler** [comment]
@scott-he 可视化 Markdown 编辑器推荐试试 [CuteMarkEd](http://cloose.github.io/CuteMarkEd/)，首次打开需选择“设置-样式-Github”。  

另外最新的[Visual Studio Code](https://code.visualstudio.com)，目前也已支持可视化，需要点一下右上角的侧边预览按钮。
