### ISSUE TITLE
MdCharm is no longer maintained

### ISSUE THREAD

**Issue by zhangshine** [zhangshine/MdCharm#4]
My father was diagnosed with [ALS](http://en.wikipedia.org/wiki/Amyotrophic_lateral_sclerosis) this year and I need to take care fo him. So MdCharm is no longer maintained.

**Comment by rywiki** [comment]
God bless him and your family.

**Comment by bravelee** [comment]
Hope everything goes well, God bless your father and your family.

**Comment by snowdream** [comment]
God bless you and your family.

**Comment by wiless** [comment]
Best wishes.. i have used mdcharm too

**Comment by conTroll** [comment]
Best wishes to you. I really hope things go the best possible way.
Also, thank you very much for your work.

**Comment by anodynos** [comment]
Best regards, I hope everything turns out well..

**Comment by taizilongxu** [comment]
God bless you and your family.

**Comment by cainus** [comment]
Hey... I just wanted to add my thanks for your work.  Best wishes.

**Comment by orschiro** [comment]
Thank you for your contribution to open source! MdCharm is the closest that I could found for an easy to use Markdown Table GUI.

**Comment by digglife** [comment]
祝早日康复！

**Comment by NemoTheBad** [comment]
祝福

**Comment by pecota-luizalabs** [comment]
Stay strong.

**Comment by Rearcher** [comment]
God bless you and your family,  Mdcharm is excellent!

**Comment by zhyihui** [comment]
thanks for your work, Best regards!

**Comment by weimingzhen** [comment]
祝福

**Comment by Martian101** [comment]
祝早日康复！

**Comment by zync-mzy** [comment]
祝早日康复！

**Comment by Cnly** [comment]
God bless you and your family.

**Comment by silveringsea** [comment]
God bless him and your family

**Comment by y1yang1** [comment]
祝早日康复

**Comment by zhangxiaoya** [comment]
Thanks for your works, and best wishes for your family!

**Comment by huntinux** [comment]
早日康复！

**Comment by walkonroad** [comment]
best wishes to your family!
